name: web-app-api
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://139.155.74.121:6006/hotel-plus?useUnicode=true&characterEncoding=utf-8&useSSL=false&tcpRcvBuf=1024000&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: hotel-plus
    password: 123456
locationTemp: /Users/singer/data #上传文件的临时目录

